services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/ASP.NET/https:/root/.aspnet/https:ro
    depends_on:                           
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "1"
      SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - ${DB_VOLUME_PATH}:/var/opt/mssql/data